### ISSUE TITLE
Audit of Applications (Windows, Microsoft, Autodesk) installed for Cape Town draughtsmen

### ISSUE THREAD

**Issue by TarrynWells** [DRA-Projects-SA-Pty-Ltd/Design-Office-Autodesk-Upgrade#12]
Investigate what applications are currently installed on all draughtsmens workstations in Cape Town.

**Comment by SamanthaBrady** [comment]
[Cape Town Autodesk 2020 D.O. Roles and Applications.xlsx](https://github.com/DRA-Projects-SA-Pty-Ltd/Design-Office-Autodesk-Upgrade/files/3619967/Cape.Town.Autodesk.2020.D.O.Roles.and.Applications.xlsx)

**Comment by SamanthaBrady** [comment]
@GeorgeYoungDRA  - uploaded CT requirements, more to follow.
