### ISSUE TITLE
Audit of Applications (Windows, Microsoft, Autodesk) installed for Toronto draughtsmen

### ISSUE THREAD

**Issue by TarrynWells** [DRA-Projects-SA-Pty-Ltd/Design-Office-Autodesk-Upgrade#13]
Investigate what applications are currently installed on all draughtsmens workstations in Toronto

**Comment by RobertSzykowski** [comment]
Completed audit of CAD (only) install requirements for DOs Toronto & Montreal (Josh).
We have a list of all designers and what to install for each.

**Comment by TarrynWells** [comment]
@RobertSzykowski Please will you upload the Software requirements for the Toronto and Montreal Offices so that we can create a "base" image for you to begin with.
