### ISSUE TITLE
Test AutoCAD Plant 3D P&ID Upgrading (2019-2020)

### ISSUE THREAD

**Issue by TarrynWells** [DRA-Projects-SA-Pty-Ltd/Design-Office-Autodesk-Upgrade#20]
Find out who will test for P&ID.

**Comment by TarrynWells** [comment]
Had a meeting with Herman, Michael, Adri, Magda and Elona. Adri and Elona to be responsible for Testing.
Adri to arrange testing Hardware with @RobertSzykowski 
Elona Waiting on @TarrynWells for feedback on test environment

**Comment by adrivanrooyen** [comment]
Tested 8 projects in Toronto office.  Copied and migrated successfully in 2020.   Tested all functionality and everything is ok.  Tested Report creator application and no issues. 

Boolean property is still not functioning.  This problem occured when we upgraded from version 2018 to 2019.  Logged a service call with Autodesk - they will fix the issue in a new version. (Not confirmed in which version though)

Will test projects in SA office next week when Elona is available.

**Comment by TarrynWells** [comment]
@ELONA252 You VM is currently in progress. You will have access by COB Today for testing.

**Comment by TarrynWells** [comment]
@ELONA252 Virtual Machine setup complete and access granted.

**Comment by adrivanrooyen** [comment]
Tested the following projects with Elona on SA side:  Kamoa-kakula, Waterberg, Waterg 400 ktpm and Makhado .
Everything functioned properly and no issues occured.

To concluded: we did not find any issues with the testing of PID 2020 version.
