### ISSUE TITLE
Create space for Autodesk Software to be saved Cape Town

### ISSUE THREAD

**Issue by TarrynWells** [DRA-Projects-SA-Pty-Ltd/Design-Office-Autodesk-Upgrade#28]

**Comment by LourantdelaRey** [comment]
\\arch01-cpt-za\Archive\Software\Autodesk

**Comment by GeorgeYoungDRA** [comment]
Under Autodesk I've created a 2020 folder and there copied installation files for AutoCAD, Civil 3D, NW Manage, Revit, Robot Struct Analysis. This will cover the requirements of the Engineering compliment who will not deploy the SCCM Image process. In addition, created a folder for Object enablers and one for Viewers.
![2019-09-27 02-42-25 PM](https://user-images.githubusercontent.com/54702860/65770165-c5d38200-e135-11e9-9100-e9dd44051f07.png)
![2019-09-27 02-42-51 PM](https://user-images.githubusercontent.com/54702860/65770167-c8ce7280-e135-11e9-92be-b17fc57f69d3.png)
![2019-09-27 02-43-11 PM](https://user-images.githubusercontent.com/54702860/65770174-cbc96300-e135-11e9-9127-c40752d68d14.png)
