### ISSUE TITLE
Test new license manager software

### ISSUE THREAD

**Issue by RobertSzykowski** [DRA-Projects-SA-Pty-Ltd/Design-Office-Autodesk-Upgrade#35]
Test the upgraded license manager software with CAD 2020

**Comment by joshualoureiro** [comment]
Autodesk License Manager (used by the Toronto and Montreal offices) for the license server has been updated to version 11.16.  It is succesffuly providing network licenses for 2020 products as tested by Robert.

**Comment by RobertSzykowski** [comment]
Tested with AEC network license for Advanced Steel 2020. No issues.
